### ISSUE TITLE
PortAudioのバージョンアップ

### ISSUE THREAD

**Issue by tetsuzawa** [kudolab/douki_c_programs#3]
# やること

MakefileのPortAudioのバージョンを19.6.0から19.7.0に変更する
https://github.com/kudolab/douki_c_programs/blob/50d2a2d5b0ee37cf8f9f777ea7952486952e8319/Makefile#L197-L236

# 手順

1. このrepoをcloneする
2. ローカルでブランチを切る
    ```sh
    git switch -c <ブランチ名>
    ```
    ブランチ名は`update-portaudio-version`などでいい
3. コードを修正する
4. githubにpush
    ```sh
    git push origin HEAD
    ```
5. github上でPull Requestを作ってレビューをお願いする
6. OKならmainにマージ

**Comment by tetsuzawa** [comment]
@neqonagomiya 

時間あるときにissue読んで作業進めてみて。
わからなかったらこのissueにコメント書き足して！

**Comment by kaedenagomiya** [comment]
@tetsuzawa 
Makefileの197行から236行間のportaudioのバージョンを19.6.0から19.7.0に変更しました。
これによってM1Macでも対応可能です。
